language: node_js
node_js:
  - "node"
  - "8"
cache:
  directories:
    - node_modules/
install:
  - npm install
  - npm install -g vuepress@0.14.2
script:
  - vuepress build
deploy:
  provider: surge
  project: .vuepress/dist/
  domain: musik.surge.sh
  skip_cleanup: true